version: "3.8"

networks:
  data:
    name: main

services:

  redis:
    image: redis/redis-stack-server:latest
    env_file: ./.env.dev
    restart: always
    networks: [ data ]
    # CMD ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\" --save 60 1 --loglevel warning"]
    ports: [ 6379 ]
    volumes:
      - ./data/redis/data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-test}
      - REDIS_REPLICATION_MODE=master
      - REDIS_ARGS="--requirepass \"$REDIS_PASSWORD\" --save 60 1 --loglevel warning"
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  postgres:
    build: ./postgres
    env_file: ./.env.dev
    restart: always
    networks: [ data ]
    ports: [ 5432 ]
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  rabbitmq:
    build: ./rabbitmq
    env_file: ./.env.dev
    restart: always
    networks: [ data ]
    ports: [5672, 15672, 15692]
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER:-test}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-test}
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224
