version: "3.8"

networks:
  apps:
    name: main

services:

  # data

  redis:
    image: redis/redis-stack-server:latest
    env_file: ./.env.dev
    restart: always
    networks: [ apps ]
    # CMD ["sh", "-c", "exec redis-server --requirepass \"$REDIS_PASSWORD\" --save 60 1 --loglevel warning"]
    ports: [ 6379 ]
    volumes:
      - ./data/redis/data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-test}
      - REDIS_REPLICATION_MODE=master
      - REDIS_ARGS="--requirepass \"$REDIS_PASSWORD\" --save 60 1 --loglevel warning"
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  postgres:
    build: ./postgres
    image: postgres:15beta2-alpine3.16
    env_file: ./.env.dev
    restart: always
    networks: [ apps ]
    ports: [ 5432 ]
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  rabbitmq:
    build: ./rabbitmq
    env_file: ./.env.dev
    restart: always
    networks: [ apps ]
    ports: [ 5672, 15672, 15692 ]
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER:-test}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-test}
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  eventstore:
    image: eventstore/eventstore:21.10.9-alpha-arm64v8
    env_file: ./.env.dev
    restart: always
    networks: [ apps ]
    ports: [ 1113, 2113 ]
    volumes:
      - ./data/eventstore/data:/var/lib/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    healthcheck:
      test: exit 0
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  # apps

  user:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
      target: build
    image: user:latest
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8001:3000 ]
    command: yarn start:dev user
    volumes:
      - ./apps/user:/usr/src/app/apps/user
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=user-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/users
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
      - EVENTSTORE_URL=tcp://eventstore:1113
    depends_on:
      - postgres
      - eventstore
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  project:
    build:
      context: .
      dockerfile: apps/project/Dockerfile
      target: build
    image: project:latest
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8002:3000 ]
    command: yarn start:dev project
    volumes:
      - ./apps/project:/usr/src/app/apps/project
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=project-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/projects
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
      - EVENTSTORE_URL=tcp://eventstore:1113
    depends_on:
      - postgres
      - eventstore
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  issue-service:
    build:
      context: ./packages/apps/issue
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8003:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/issue:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=issue-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/issues
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  search-service:
    build:
      context: ./packages/apps/search
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8004:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/search:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=search-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/search
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  auth-service:
    build:
      context: ./packages/apps/auth
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8005:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/auth:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=auth-service
      - AUTH_ACCESS_TOKEN_LIFESPAN=${AUTH_ACCESS_TOKEN_LIFESPAN:-3600};
      - AUTH_REFRESH_TOKEN_LIFESPAN=${AUTH_REFRESH_TOKEN_LIFESPAN:-2419200};
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - user-service
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  notification-service:
    build:
      context: ./packages/apps/notification
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8006:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/notification:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=notification-service
      - SMTP_URL=smtp://${SMTP_USER}:${SMTP_PASSWORD}@${SMTP_HOST}
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/notifications
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  report-service:
    build:
      context: ./packages/apps/report
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8007:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/report:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=report-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/issues
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  billing-service:
    build:
      context: ./packages/apps/billing
      target: build # production
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 8008:3000 ]
    command: yarn start:dev
    volumes:
      - ./packages/apps/billing:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=billing-service
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@db:5432/billing
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  minio:
    image: minio/minio:latest
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    command: "server /data --console-address ':9001'"
    ports: [ 9000, 9001 ]
    volumes:
      - ./minio/data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-test}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-test}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-test}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-test}
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  nginx:
    build: ./nginx
    env_file: ./.env.dev
    restart: on-failure
    networks: [ apps ]
    ports: [ 80, 443 ]
    volumes:
      - ./nginx/nginx:/etc/nginx:ro
      - ./nginx/jaeger-config.json:/etc/jaeger-config.json:ro
      - ./nginx/swagger-ui:/var/www/swagger-ui:ro
      - ./packages/services/web/dist:/usr/share/nginx/html:ro
    environment:
      - HOST=${HOST:-localhost}
      - API_VERSION=${API_VERSION:-v1}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:60}
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224
  # web:
  #   build:
  #     context: ./packages/apps/web
  #     target: build # production
  #   env_file: ./.env.dev
  #   restart: unless-stopped
  #   command: yarn dev
  #   ports: [ 3000 ]
  #   volumes:
  #     - ./packages/apps/web:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_OPTIONS=--openssl-legacy-provider
  #     - SKIP_PREFLIGHT_CHECK=true
  #     - CHOKIDAR_USEPOLLING=true
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-test}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-test}
