route:
  receiver: 'mail'
  repeat_interval: 4h
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: ${SMTP_HOST} # 'smtp.gmail.com:465'
        auth_username: ${SMTP_USER} # 'your_mail@gmail.com'
        auth_password: ${SMTP_PASSWORD} # ""
        from: ${SMTP_USER} # 'your_mail@gmail.com'
        to: ${ADMIN_EMAIL} # 'some_mail@gmail.com'
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'

templates:
- /etc/alertmanager/notifications.tmpl

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the instance and alertname are the same.
  equal: ['instance', 'alertname']
