version: "3.8"

services:

  # data

  redis:
    volumes:
      - ./redis/data:/data
    env_file: ../.env.dev
    restart: unless-stopped

  postgres:
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file: ../.env.dev
    restart: unless-stopped

  rabbitmq:
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    env_file: ../.env.dev
    restart: unless-stopped

  eventstore:
    volumes:
      - ./eventstore/data:/var/lib/eventstore
    env_file: ../.env.dev
    restart: unless-stopped

  minio:
    volumes:
      - ./minio/data:/data
    env_file: ../.env.dev
    restart: unless-stopped

  mc:
    env_file: ../.env.dev
    restart: unless-stopped

  # apps

  keycloak:
    env_file: ../.env.dev
    environment:
      - KC_HOSTNAME=localhost
    command: start-dev --import-realm
    restart: unless-stopped

  workspace-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=workspace-svc
        - NODE_ENV=development
    volumes:
      - ../apps/workspace-svc:/usr/src/app/apps/workspace-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev workspace-svc
    restart: unless-stopped

  issue-command-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=issue-command-svc
        - NODE_ENV=development
    volumes:
      - ../apps/issue-command-svc:/usr/src/app/apps/issue-command-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev issue-command-svc
    restart: unless-stopped

  issue-query-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=issue-query-svc
        - NODE_ENV=development
    volumes:
      - ../apps/issue-query-svc:/usr/src/app/apps/issue-query-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev issue-query-svc
    restart: unless-stopped

  notification-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=notification-svc
        - NODE_ENV=development
    volumes:
      - ../apps/notification-svc:/usr/src/app/apps/notification-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev notification-svc
    restart: unless-stopped

  search-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=search-svc
        - NODE_ENV=development
    volumes:
      - ../apps/search-svc:/usr/src/app/apps/search-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev search-svc
    restart: unless-stopped

  report-svc:
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=report-svc
        - NODE_ENV=development
    volumes:
      - ../apps/report-svc:/usr/src/app/apps/report-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    env_file: ../.env.dev
    command: nest start:dev report-svc
    restart: unless-stopped

  sso-proxy:
    env_file: ../.env.dev
    environment:
      - OAUTH2_PROXY_COOKIE_SECURE=false # no https
    restart: unless-stopped

  gateway:
    build: ../apps/gateway
    volumes:
      - ../apps/gateway/nginx:/etc/nginx:ro
      - ../apps/gateway/jaeger-config.json:/etc/jaeger-config.json:ro
      - ../apps/gateway/swagger-ui:/var/www/swagger-ui:ro
    env_file: ../.env.dev
    environment:
      - HOST=localhost
    restart: unless-stopped

  # monitoring

  loki:
    env_file: ../.env.dev
    restart: unless-stopped

  fluent-bit:
    env_file: ../.env.dev
    restart: unless-stopped

  jaeger:
    env_file: ../.env.dev
    restart: unless-stopped

  prometheus:
    env_file: ../.env.dev
    restart: unless-stopped

  grafana:
    env_file: ../.env.dev
    restart: unless-stopped
