version: "3.8"

networks:
  apps:
    name: main
  monitoring:
    name: main

services:

  # data

  redis:
    image: redis/redis-stack-server:latest
    networks: [ apps ]
    ports: [ 6379 ]
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_ARGS="--requirepass \"$REDIS_PASSWORD\" --save 60 100 --loglevel warning"
      - REDIS_PASSWORD=${REDIS_PASSWORD:-test}
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  postgres:
    image: postgres:15beta2-alpine3.16
    networks: [ apps ]
    ports: [ 5432 ]
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-test}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  rabbitmq:
    image: rabbitmq:management-alpine
    networks: [ apps ]
    ports: [ 5672, 15672, 15692 ]
    volumes:
      - ./rabbitmq/plugins/:/opt/rabbitmq/plugins/"
      - ./rabbitmq/init.sh:/init.sh"
    environment:
      - RABBITMQ_PID_FILE=/var/lib/rabbitmq/mnesia/rabbitmq
      - RABBITMQ_USER=${RABBITMQ_USER:-test}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-test}
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange rabbitmq_prometheus && chmod +x /init.sh && /init.sh"
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  eventstore:
    image: eventstore/eventstore:21.10.9-alpha-arm64v8
    networks: [ apps ]
    ports: [ 1113, 2113 ]
    environment:
      - EVENTSTORE_USER=${EVENTSTORE_USER:-test}
      - EVENTSTORE_PASSWORD=${EVENTSTORE_PASSWORD:-test}
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=all
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  minio:
    image: minio/minio:latest
    networks: [ apps ]
    ports: [ 9000, 9001 ]
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-test}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-test}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-test}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-test}
    command: "bash -c 'server /data --console-address ':9001''"
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  mc:
    image: minio/mc:latest
    networks: [ apps ]
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-test}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD:-test}
    entrypoint: >
      /bin/sh -c " /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD}; && /usr/bin/mc rm -r --force myminio/loki; && /usr/bin/mc mb myminio/loki; && /usr/bin/mc policy set public myminio/loki; && exit 0; "
    depends_on:
      - minio

  # apps

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    networks: [ apps ]
    ports: [ 8000:8080, 8443 ]
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
      - ./keycloak-magic-link-0.19.jar:/opt/keycloak/providers/keycloak-magic-link-0.19.jar
    environment:
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER:-test}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD:-test}
      - KC_METRICS_ENABLED=true # https://localhost:8000/metrics
      - KC_HEALTH_ENABLED=true # https://localhost:8000/health
      - KC_DB=postgres
      - KC_DB_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@postgres:5432/workspace
      - KC_DB_USERNAME=${POSTGRES_USER:-test}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-test}
    depends_on:
      - postgres
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  workspace-svc:
    image: taskapp/workspace-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3001:3000, 50051 ]
    environment:
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      - KEYCLOAK_URL=http://keycloak:8000/realms/master
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
    depends_on:
      - keycloak
      - rabbitmq
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  issue-command-svc:
    image: taskapp/issue-command-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3002:3000, 50052 ]
    environment:
      - EVENTSTORE_URL=esdb://${EVENTSTORE_USER:-test}:${EVENTSTORE_PASSWORD:-test}@eventstore:1113
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - eventstore
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  issue-query-svc:
    image: taskapp/issue-query-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3003:3000, 50053 ]
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@postgres:5432/issues
      - EVENTSTORE_URL=esdb://${EVENTSTORE_USER:-test}:${EVENTSTORE_PASSWORD:-test}@eventstore:1113
    depends_on:
      - postgres
      - eventstore
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  notification-svc:
    image: taskapp/notification-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3004:3000, 50054 ]
    environment:
      - SMTP_URL=smtp://${SMTP_USER:-test}:${SMTP_PASSWORD:-test}@${SMTP_HOST:-test}
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@postgres:5432/notifications
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  search-svc:
    image: taskapp/search-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3005:3000, 50055 ]
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@postgres:5432/search
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  report-svc:
    image: taskapp/report-svc:${TAG:-latest}
    networks: [ apps ]
    ports: [ 3006:3000, 50056 ]
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER:-test}:${POSTGRES_PASSWORD:-test}@postgres:5432/metrics
      - RABBITMQ_URL=amqp://${RABBITMQ_USER:-test}:${RABBITMQ_PASSWORD:-test}@rabbitmq:5672
      - REDIS_URL=redis://:${REDIS_PASSWORD:-test}@redis:6379
    depends_on:
      - postgres
      - rabbitmq
      - redis
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  sso-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    networks: [ apps ]
    ports: [ 4180 ]
    entrypoint:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_COOKIE_SECRET=${SECRET:-test}
      - OAUTH2_PROXY_COOKIE_DOMAINS=localhost # Required so cookie can be read on all subdomains
      - OAUTH2_PROXY_WHITELIST_DOMAINS=localhost # Required to allow redirection back to original requested target
      - OAUTH2_PROXY_PROVIDER=oid
      - OAUTH2_PROXY_CLIENT_ID=sso-proxy
      - OAUTH2_PROXY_CLIENT_SECRET=${SECRET:-test}
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8000/realms/master'
      - OAUTH2_PROXY_REDIRECT_URL=http://keycloak:8000/oauth2/callback'
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true # skip email validation
      - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=sub # skip email validation
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true # set response header with user data
    depends_on:
      - keycloak
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  gateway:
    image: taskapp/gateway:${TAG:-latest}
    networks: [ apps ]
    ports: [ 80, 443, 8080 ]
    environment:
      - API_VERSION=${API_VERSION:-v1}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-30}
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
      - HOST=${HOST}
    depends_on:
      - sso-proxy
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224

  # monitoring(apm)

  loki:
    image: grafana/loki:latest
    networks: [ monitoring ]
    ports: [ 3100 ]
    user: root
    volumes:
      - ./loki/config.yml:/etc/loki/config.yaml:ro
      - ./loki/alerts.yml:/etc/loki/rules/alerts/rules.yml:ro
    environment:
      # the dot in the S3 address for MinIO is used because there is no need to specify AWS Region
      - MINIO_URL=http://${MINIO_USER:-test}:${MINIO_PASSWORD:-test}@minio.:9000/loki
    command: -config.file=/etc/loki/config.yaml
    depends_on:
      - minio

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    networks: [ monitoring ]
    ports: [ 24224, 24224:24224/udp ]
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - loki

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks: [ monitoring ]
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778
      - 16686
      - 14268
      - 14250
      - 9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  prometheus:
    image: prom/prometheus:latest
    networks: [ monitoring ]
    ports: [ 9090 ]
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/config.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    command:
      - "--config.file=/etc/prometheus/config.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=7d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    depends_on:
      - minio

  grafana:
    image: grafana/grafana:latest
    networks: [ monitoring ]
    ports: [ 3033:3000 ]
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-test}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-test}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
      - jaeger
      - loki

  