version: "3.8"

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:
  prometheus_data:
  eventstore_data:
  minio_data:
  grafana_data:
  alertmanager_data:

services:

  # data

  redis:
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  rabbitmq:
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq"
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on_failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  eventstore:
    volumes:
      - eventstore_data:/var/lib/eventstore
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  minio:
    volumes:
      - minio_data:/data
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  mc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  # apps

  keycloak:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  workspace-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  issue-command-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  issue-query-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  notification-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  search-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  report-svc:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  sso-proxy:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1
          
  gateway:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  # monitoring

  loki:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  fluent-bit:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  jaeger:
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  prometheus:
    volumes:
      - prometeus_data:/prometheus
    depends_on:
      - node-exporter
      - cadvisor
      - nginx-exporter
      - postgres-exporter
      - redis-exporter
      - rabbitmq-exporter
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  grafana:
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    networks: [ monitoring ]
    ports: [ 8081:8080 ]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  node-exporter:
    image: prom/node-exporter:latest
    networks: [ monitoring ]
    ports: [ 9100 ]
    command:
      - "—-path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:edge
    networks: [ monitoring ]
    ports: [ 9113 ]
    environment:
      - nginx.scrape-uri=nginx:80/metrics
    depends_on:
      - nginx
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  postgres-exporter:
    image: bitnami/postgres-exporter:latest
    networks: [ monitoring ]
    ports: [ 9187 ]
    environment:
      - DATA_SOURCE_NAME=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  redis-exporter:
    # we use this since only redis enterprice has native prometheus supporting
    image: oliver006/redis_exporter
    networks: [ monitoring ]
    ports: [ 9121 ]
    environment:
      - REDIS_ADDR=redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

  alertmanager:
    image: prom/alertmanager:latest
    networks: [ monitoring ]
    ports: [ 9093 ]
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - ./alertmanager/notifications.tmpl:/etc/alertmanager/notifications.tmpl:ro
    command:
      - "--storage.path=/alertmanager"
      - "--config.file=/etc/alertmanager/config.yml"
    restart: always
    healthcheck:
      test: exit 0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
          pids: 1

 



