global:
  scrape_interval: 15s
  evaluation_interval: 5s
  # scrape_timeout:     1m
  # query_log_file: <string>
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
  - job_name: "prometheus"
    # scrape_interval: 5s # Override the global
    static_configs:
      - targets: ["host.docker.internal:3001"]
  - job_name: "docker"
    static_configs:
      - targets: ["docker.for.mac.host.internal:9323"] # Linux: 'localhost:9323'
  # - job_name: cadvisor
  #   scrape_interval: 5s # Override the global
  #   static_configs:
  #   - targets: ["cadvisor:8080"]
  - job_name: "backend-metrics"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"] # Linux: 'localhost:8080'