global:
  scrape_interval: 15s
  evaluation_interval: 5s
  external_labels:
    monitor: "prometheus-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"] # docker.for.mac.host.internal:9090
  - job_name: docker
    static_configs:
      - targets: ["localhost:9323"] # docker.for.mac.host.internal:9323
  - job_name: prod_node
    static_configs:
      - targets: ["put_prod_node_exporter_host:9100"]
  - job_name: prod_docker
    static_configs:
      - targets: ["put_prod_cadvisor_exporter_host:8081"]
      # data
  - job_name: prod_redis
    static_configs:
      - targets: ["put_prod_redis_exporter_host:9121"]
  - job_name: prod_postgres
    static_configs:
      - targets: ["put_prod_postgres_exporter_host:9187"]
  - job_name: prod_mongodb
    static_configs:
      - targets: ["put_prod_mongo_exporter_host:9216"]
  - job_name: prod_rabbitmq
    static_configs:
      - targets: ["put_prod_rabbitmq_host:15692"]
  - job_name: prod_minio_cluster
    metrics_path: "/minio/v2/metrics/cluster"
    scheme: "http"
    static_configs:
      - targets: ["put_prod_minio_host:9000"]
  - job_name: prod_minio_node
    metrics_path: "/minio/v2/metrics/node"
    scheme: "http"
    static_configs:
      - targets: ["put_prod_minio_host:9000"]
    # sso
  - job_name: prod_keycloak"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_keycloak_host:8080"]
  # apps
  - job_name: prod_workspace_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_workspace_svc_host:50051"]
  - job_name: prod_notification_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_notification_svc_host:50052"]
  - job_name: prod_search_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_search_svc_host:50053"]
  - job_name: prod_report_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_report_svc_host:50054"]
  - job_name: prod_project_command_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_project_command_svc_host:50055"]
  - job_name: prod_project_query_svc"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["put_prod_project_query_svc_host:50056"]
  # - job_name: prod_gateway
  #   static_configs:
  #     - targets: ["put_prod_nginx_exporter_host:9113"]

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  # send to alertmanager
  alertmanagers:
    - scheme: "http"
      static_configs:
        - targets: ["alertmanager:9093"] # host.docker.internal:9093

