version: '3.9'

# local env
# 1. use own or dev data and sso services

services:
  # data

  rabbitmq:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  redis:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./redis/data:/data

  postgres:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  mongodb:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./mongodb/data:/data/db

  cassandra:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./cassandra/data:/var/lib/cassandra

  clickhouse:
    restart: unless-stopped
    env_file: ../env.local
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse/

  # sso

  keycloak:
    restart: unless-stopped
    env_file: ../env.local
    command: start-dev --import-realm
    environment:
      - KC_HOSTNAME=localhost

  # misc

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    networks: [apps]
    ports: [1025:1025, 8025:8025]
    healthcheck:
      test: exit 0

  # apps

  workspace-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev workspace-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=workspace-svc
        - NODE_ENV=development
    volumes:
      - ../apps/workspace-svc:/usr/src/app/apps/workspace-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  notification-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev notification-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=notification-svc
        - NODE_ENV=development
    volumes:
      - ../apps/notification-svc:/usr/src/app/apps/notification-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  search-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev search-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=search-svc
        - NODE_ENV=development
    volumes:
      - ../apps/search-svc:/usr/src/app/apps/search-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  report-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev report-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=report-svc
        - NODE_ENV=development
    volumes:
      - ../apps/report-svc:/usr/src/app/apps/report-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  project-command-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev project-command-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=project-command-svc
        - NODE_ENV=development
    volumes:
      - ../apps/project-command-svc:/usr/src/app/apps/project-command-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  project-query-svc:
    restart: unless-stopped
    env_file: ../env.local
    command: nest start:dev project-query-svc
    build:
      context: ../
      target: build
      args:
        - SERVICE_NAME=project-query-svc
        - NODE_ENV=development
    volumes:
      - ../apps/project-query-svc:/usr/src/app/apps/project-query-svc
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on: !reset []

  gateway:
    restart: unless-stopped
    env_file: ../env.local
    build: ../apps/gateway
    volumes:
      - ../apps/gateway/nginx:/etc/nginx:ro
      - ../apps/gateway/jaeger-config.json:/etc/jaeger-config.json:ro
    environment:
      - HOST=localhost
    depends_on: !reset []
