version: '3.9'

# dev env
# 1. use own data and sso services

services:
  # apps

  workspace-svc:
    image: taskapp/workspace-svc-dev:${TAG:-latest}

  notification-svc:
    image: taskapp/notification-svc-dev:${TAG:-latest}

  search-svc:
    image: taskapp/search-svc-dev:${TAG:-latest}

  report-svc:
    image: taskapp/report-svc-dev:${TAG:-latest}

  project-command-svc:
    image: taskapp/project-command-svc-dev:${TAG:-latest}

  project-query-svc:
    image: taskapp/project-query-svc-dev:${TAG:-latest}

  gateway:
    image: taskapp/gateway-dev:${TAG:-latest}
