version: '3.9'

# staging env
# 1. use prod data & sso services

services:
  # data

  rabbitmq:
    profiles:
      - none
    
  redis:
    profiles:
      - none

  postgres:
    profiles:
      - none

  mongodb:
    profiles:
      - none

  cassandra:
    profiles:
      - none
  
  clickhouse:
    profiles:
      - none
  
  minio:
    profiles:
      - none

  mc:
    profiles:
      - none

  # sso

  keycloak:
    profiles:
      - none

  # apps

  workspace-svc:
    image: taskapp/workspace-svc-staging:${TAG:-latest}

  notification-svc:
    image: taskapp/notification-svc-staging:${TAG:-latest}

  search-svc:
    image: taskapp/search-svc-staging:${TAG:-latest}

  report-svc:
    image: taskapp/report-svc-staging:${TAG:-latest}

  project-command-svc:
    image: taskapp/project-command-svc-staging:${TAG:-latest}

  project-query-svc:
    image: taskapp/project-query-svc-staging:${TAG:-latest}
  
  gateway:
    image: taskapp/gateway-staging:${TAG:-latest}


  

