global:
  scrape_interval: 15s
  evaluation_interval: 5s
  external_labels:
    monitor: "prometheus-monitor"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["host.docker.internal:9090"] # prometheus:9090
  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9100"] # node-exporter:9100
  - job_name: docker
    static_configs:
      - targets: ["docker.for.mac.host.internal:9323"] # Linux: 'localhost:9323'
  - job_name: cadvisor
    static_configs:
      - targets: ["host.docker.internal:8081"] # cadvisor:8081
  - job_name: postgres
    static_configs:
      - targets: ["host.docker.internal:9187"] # postgres-exporter:9187
  - job_name: redis
    static_configs:
      - targets: ["host.docker.internal:9121"] # redis-exporter:9121
  - job_name: rabbitmq
    static_configs:
      - targets: ["host.docker.internal:15692"] # rabbitmq:15692
  - job_name: nginx
    static_configs:
      - targets: ["host.docker.internal:9113"] # nginx-exporter:9113
  - job_name: minio
    metrics_path: "/minio/v2/metrics/cluster"
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:9000"] # minio:9000
  - job_name: minio-node
    metrics_path: "/minio/v2/metrics/node"
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:9000"] # minio:9000
  # - job_name: "worspace-sevice"
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:3001"] # Linux: 'localhost:3001'

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  # send to alertmanager
  alertmanagers:
    - scheme: "http"
      static_configs:
        - targets: ["host.docker.internal:9093"] # alertmanager:9093



