name: "run tests for dev"

on:
  pull_request:
    types: [opened, synchronize, reopened] # synchronize is target feature branch update
    branches: [dev]

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true # start latest instead of current

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install newman
        run: npm install -g newman

      # 2. Run Tests
      - name: Run Unit & Integration Tests
        run: mv .env.example .env; npm run install; npm run build; npm run lint; npm run test:jest;
      - name: Run E2E Tests
        run: npm run test:e2e;
        # run: newman run NewmanDemo.postman_collection.json -e ReqResDev.postman_environment.json 
