global:
  scrape_interval: 15s
  evaluation_interval: 5s
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9100"] # node-exporter:9100
  - job_name: docker
    static_configs:
      - targets: ["docker.for.mac.host.internal:9323"] # Linux: 'localhost:9323'
  - job_name: cadvisor
    static_configs:
    - targets: ["host.docker.internal:8081"] # cadvisor:8081
  - job_name: prometheus
    static_configs:
      - targets: ["host.docker.internal:9090"] # prometheus:9090
  - job_name: nginx
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:9113"] # nginx-exporter:9113
  - job_name: postgres
    static_configs:
      - targets: ["host.docker.internal:9187"] # postgres-exporter:9187
  - job_name: redis
    static_configs:
      - targets: ["host.docker.internal:9121"] # redis-exporter:9121
  - job_name: rabbitmq
    static_configs:
      - targets: ["host.docker.internal:9419"] # rabbitmq-exporter:9419
  - job_name: minio
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:9000"] # minio:9000
  - job_name: minio
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: ["host.docker.internal:9000"] # minio:9000

  # - job_name: "project-sevice"
  #   metrics_path: "/metrics"
  #   static_configs:
  #     - targets: ["host.docker.internal:8005"] # Linux: 'localhost:8005'




